### ISSUE TITLE
Grid lines on downloaded image

### ISSUE THREAD

**Issue by yokotsumo** [snorpey/distort-grid#3]
This plugin is great but I have only one issue with it. 

There are two canvases, one for the grid and one for the image. On the image canvas, zebra lines are added to complete the grid and each time a deformation is added, lines from the grid canvas are added to the image canvas. 

Where would you go in the code to remove any of these lines from the image canvas?

**Comment by snorpey** [comment]
hey @yokotsumo thank you for using the experiment.

are you referring to these diagonal lines in an exported image?
![distorted-image](https://cloud.githubusercontent.com/assets/166433/6218181/d218607a-b61b-11e4-935e-5f7a99601929.png)

those lines are actually not added intentionally. they are a result of an anti-aliasing issues (i suspect) and i'm not quite sure how to make them go away. basically the whole image is divided into triangles which are then distorted.

so far, i haven't been able to make the triangles line up perfectly. so there's always a 1px "gap" between them.

you can find the distortion code here: https://github.com/snorpey/distort-grid/blob/develop/scripts/util/distort.js

i learned a bunch about the image transformations from @migurski's [web site](http://mike.teczno.com/notes/canvas-warp.html) and his [repo](https://github.com/migurski/canvas-warp)...

sorry i can't give you a satisfactory solution to the problem. please do let me know if you you figure out a solution to this issue.

**Comment by yokotsumo** [comment]
I made them disappear in most cases by ding this:
- expand top triangle diagonal by 1px;
- expand bottom triangle by 1px on all sides;
- remove both ctx.fill();

**Comment by snorpey** [comment]
hey @yokotsumo thank you so much for that tip. i just pushed a change that addresses this issue. it's not 100% perfect yet, but much better. thanks again!

**Comment by yokotsumo** [comment]
Hello Georg,


I am glad you integrated the change. 


I am currently working on a personal project and would like to integrate the grid functionnality in it. My problem is that I have been working on this project with a standard WordPress/jQuery architecture and that I am quite new to require.JS.

Even after having read the require.JS documentation and searched the internet, it is hard for me to figure out how to integrate a require.JS package into another project (if possible). I would like to be able to call the ‘fileLoaded( event )’ function directly from the original script.

Would you have an idea on how to do that?


Sincerely.






Envoyé depuis Windows Mail





De : georg fischer
Envoyé : ‎mardi‎ ‎17‎ ‎février‎ ‎2015 ‎00‎:‎01
À : snorpey/distort-grid
Cc : Bertrand Rocquet





hey @yokotsumo thank you so much for that tip. i just pushed a change that addresses this issue. it's not 100% perfect yet, but much better. thanks again!

**Comment by snorpey** [comment]
hey @yokotsumo in this project i'm using requirejs just for loading dependencies.

what you could do in your project is to take all javascript files and rip out the requirejs code (basically the ``define( [ ... ],function(){ ... } )`` stuff in every file) and then just load them with a bunch of regular ``<script>`` tags. you may need to play with the order of them a little bit to get them to work.

as an alternative, you could also try to make one big javascript file that contains all functions of this project.

let me know if this works for you.

**Comment by yokotsumo** [comment]
Hi Georg,


thanks for the update. I figured out how to use it as is, or nearly. It was faster.


Sincerely.






Envoyé depuis Windows Mail





De : georg fischer
Envoyé : ‎mercredi‎ ‎18‎ ‎février‎ ‎2015 ‎11‎:‎40
À : snorpey/distort-grid
Cc : Bertrand Rocquet





hey @yokotsumo in this project i'm using requirejs just for loading dependencies.

what you could do in your project is to take all javascript files and rip out the requirejs code (basically the define( [ ... ],function(){ ... } ) stuff in every file) and then just load them with a bunch of regular <script> tags. you may need to play with the order of them a little bit to get them to work.

as an alternative, you could also try to make one big javascript file that contains all functions of this project.

let me know if this works for you.
